apiVersion: v1
kind: Service
metadata:
  name: webstore-svc
  labels:
    app: webstore
spec:
  type: LoadBalancer
  selector:
    app: webstore
    version: blue    # ← this is the demo switch: blue = stable, green = broken
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
